### ISSUE TITLE
CRON broke, needs a token

### ISSUE THREAD

**Issue by dblock** [slack-ruby/slack-api-ref#19]
Looks like https://travis-ci.org/slack-ruby/slack-api-ref cron broke, the token is no longer valid. Care to help @mre? Could use a doc on what kind of token that needs to be and where to get it from for next time it breaks (maybe a CRON.md :)).

**Comment by mre** [comment]
Build should be green again. 😄 Here's the instructions for next time:
https://docs.travis-ci.com/user/deployment/pages/#Setting-the-GitHub-token
I'm actually in favor of using this link instead of the CRON.md, since the required steps could change in the future and our internal docs would then become outdated. Sounds good?

**Comment by mre** [comment]
Sure. Will do. 😄
